kind: Service
apiVersion: v1
metadata:
    name: gitops-helloworld
spec:
    selector:
        app: gitops-helloworld
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8081
    type: LoadBalancer

2021-09-19 * "KFC" "chicken"
  cba        -12.90 AUD
  food        12.90 AUD

2021-09-19 * "KFC" "chicken"
  cba        -12.90 AUD
  food        12.90 AUD
